version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    container_name: ecommmerce-backend
    user: 1000:1000
    volumes:
      - ./:/var/www
      - /var/www/vendor
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    container_name: ecommmerce-db
    restart: always
    environment:
      - MYSQL_DATABASE=chart
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33061:3306
