version: '3.8'
services:
  backend:
    build:
      args:
        - user=$USER
        - uid=1000  # need to replace with self $uid
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    container_name: ecommerce-backend
    # user: 1000:1000
    volumes:
      - ./:/var/www
      - /var/www/vendor
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  db:
    image: mysql:5.7.22
    container_name: ecommerce-db
    restart: always
    environment:
      - MYSQL_DATABASE=chart
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33061:3306

  redis:
    image: redis:6.2.6-alpine
    container_name: ecommerce-redis
    volumes:
      - ./storage/rediusdata:/data
    ports:
      - 6379:6379